relayer.md added
ggxchain/documentation pull request #92
Opened 2023-10-13 14:00 UTC by maksym-nyrka

2023-10-13 14:39 UTC, uchu requested changes
LGTM, except that we need better emphasis that it currrently works on Brroklyn.

2023-10-13 14:39 UTC, uchu commented on src/developer-documentation/relayer/relayer.md
> +For now ETH Light Client is integrated only with Brooklyn.
@maksym-nyrka Let's make it more clear that these instructions are for Brooklyn (and to mention it's a dev chain), but the process will be similar to Sydney and mainnet.

As it's easy to get lost between chains. Maybe just to make it a bold header or kinda disclaimer.

2023-10-13 14:44 UTC, uchu commented on src/developer-documentation/relayer/relayer.md
> +For now ETH Light Client is integrated only with Brooklyn.
We just don't mention Brooklyn anywhere, so maybe a good place to make some explanation here.

2023-10-16 12:18 UTC, uchu approved these changes
LGTM

2023-10-16 12:21 UTC, akorchyn approved these changes
Great job! Thanks

2023-10-16 12:57 UTC, merged